/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialSBTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIssuer"
      | "admin"
      | "credentials"
      | "issueCredential"
      | "nextTokenId"
      | "owners"
      | "removeIssuer"
      | "verifiedIssuers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialIssued" | "IssuerAdded" | "IssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedIssuers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedIssuers",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    credentialType: string
  ];
  export type OutputTuple = [
    to: string,
    tokenId: bigint,
    credentialType: string
  ];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    credentialType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialSBT extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialSBT;
  waitForDeployment(): Promise<this>;

  interface: CredentialSBTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIssuer: TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  credentials: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        issuer: string;
        credentialType: string;
        metadataURI: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  issueCredential: TypedContractMethod<
    [_to: AddressLike, _type: string, _uri: string],
    [void],
    "nonpayable"
  >;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  owners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  removeIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedIssuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        issuer: string;
        credentialType: string;
        metadataURI: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [_to: AddressLike, _type: string, _uri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAdded"
  ): TypedContractEvent<
    IssuerAddedEvent.InputTuple,
    IssuerAddedEvent.OutputTuple,
    IssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRemoved"
  ): TypedContractEvent<
    IssuerRemovedEvent.InputTuple,
    IssuerRemovedEvent.OutputTuple,
    IssuerRemovedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(address,uint256,string)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "IssuerAdded(address)": TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;
    IssuerAdded: TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;

    "IssuerRemoved(address)": TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
    IssuerRemoved: TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
  };
}
