/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofPassPassportInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPassport"
      | "nextIdNum"
      | "passports"
      | "updateScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PassportCreated" | "ProofScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPassport",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "nextIdNum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "passports",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPassport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextIdNum", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "passports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
}

export namespace PassportCreatedEvent {
  export type InputTuple = [user: AddressLike, passportId: string];
  export type OutputTuple = [user: string, passportId: string];
  export interface OutputObject {
    user: string;
    passportId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofScoreUpdatedEvent {
  export type InputTuple = [user: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [user: string, newScore: bigint];
  export interface OutputObject {
    user: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofPassPassport extends BaseContract {
  connect(runner?: ContractRunner | null): ProofPassPassport;
  waitForDeployment(): Promise<this>;

  interface: ProofPassPassportInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPassport: TypedContractMethod<
    [_metadataURI: string],
    [void],
    "nonpayable"
  >;

  nextIdNum: TypedContractMethod<[], [bigint], "view">;

  passports: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean, string] & {
        passportId: string;
        proofScore: bigint;
        isVerified: boolean;
        metadataURI: string;
      }
    ],
    "view"
  >;

  updateScore: TypedContractMethod<
    [_user: AddressLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPassport"
  ): TypedContractMethod<[_metadataURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextIdNum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "passports"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, boolean, string] & {
        passportId: string;
        proofScore: bigint;
        isVerified: boolean;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [_user: AddressLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PassportCreated"
  ): TypedContractEvent<
    PassportCreatedEvent.InputTuple,
    PassportCreatedEvent.OutputTuple,
    PassportCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProofScoreUpdated"
  ): TypedContractEvent<
    ProofScoreUpdatedEvent.InputTuple,
    ProofScoreUpdatedEvent.OutputTuple,
    ProofScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "PassportCreated(address,string)": TypedContractEvent<
      PassportCreatedEvent.InputTuple,
      PassportCreatedEvent.OutputTuple,
      PassportCreatedEvent.OutputObject
    >;
    PassportCreated: TypedContractEvent<
      PassportCreatedEvent.InputTuple,
      PassportCreatedEvent.OutputTuple,
      PassportCreatedEvent.OutputObject
    >;

    "ProofScoreUpdated(address,uint256)": TypedContractEvent<
      ProofScoreUpdatedEvent.InputTuple,
      ProofScoreUpdatedEvent.OutputTuple,
      ProofScoreUpdatedEvent.OutputObject
    >;
    ProofScoreUpdated: TypedContractEvent<
      ProofScoreUpdatedEvent.InputTuple,
      ProofScoreUpdatedEvent.OutputTuple,
      ProofScoreUpdatedEvent.OutputObject
    >;
  };
}
